apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: synara-vault-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: synara-vault
      app.kubernetes.io/name: vault
      component: server
