apiVersion: v1
kind: Service
metadata:
  name: synara-platform-admin
  labels:
    app.kubernetes.io/name: synara-platform-admin
    app.kubernetes.io/part-of: synara
spec:
  selector:
    app.kubernetes.io/name: synara-platform-admin
  ports:
    - name: http
      port: 3774
      targetPort: http
